# action.yml
name: 'Connect to VPN'
description: 'Connect Pritunl VPN'
inputs:
  vpn_config:
    description: 'VPN Config Base64 encoded'
    required: true
  vpn_pass:
    description: 'VPN Password'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash 
    - run: vpnconnect.sh ${{ inputs.vpn_config }} ${{ inputs.vpn_pass }}
      shell: bash
